### ISSUE TITLE
Obsolete time zone database

### ISSUE THREAD

**Issue by Vorticity-Flux** [choptastic/qdate#18]
Time zone database needs maintaining. Upstream erlang_localtime library gets some attention and already received several updates since the fork.

I think we would be better off if we merge the fork and use the upstream erlang_localtime directly.
Dmitry Melnikov (maintainer of upstream erlang_localtime) has agreed to merge https://github.com/choptastic/erlang_localtime/commit/6e14b6e734eca1f51944a0bba25a4179d068496b so I do not see any barriers in doing so. Please see https://github.com/dmitryme/erlang_localtime/issues/25 and comment. Thanks.

**Comment by choptastic** [comment]
Indeed. Dmitry did merge in my changes, but they still broke things as the
merge was not clean and squashed some previous functionality. I have a new
PR awaiting merger here, which fixes this:
https://github.com/dmitryme/erlang_localtime/pull/24

Once this is merged, I'll update the dependency accordingly so that
mainline erlang_localtime is used. If it's not merged soon (my last PR took
2 years for him to merge), then I'll just update my fork from mainline and
be done with it.

-Jesse
--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by Vorticity-Flux** [comment]
Great to see you are two steps ahead on this one!

**Comment by choptastic** [comment]
Dmitry is taking is time merging my PR, so I've just updated my fork of erlang_localtime to fix this.
